# Generated by Django 3.2.6 on 2022-03-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('session_hash', models.CharField(max_length=40, unique=True)),
                ('stage', models.CharField(default='1', max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('prior_experience', models.TextField(blank=True)),
                ('all_is_accurate', models.BooleanField(default=False)),
            ],
        ),
    ]
