# Generated by Django 3.2.6 on 2022-03-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='company',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
