# Generated by Django 3.2.6 on 2022-03-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0003_jobapplication_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='address_line',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='country',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='county',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='vat',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
