# Generated by Django 3.2.6 on 2022-03-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0004_auto_20220303_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='prior_experience',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='proof_business',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='proof_id',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
