# Generated by Django 3.2.6 on 2022-03-03 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_application', '0005_auto_20220303_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='all_is_accurate',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='company_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='password',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
