# Generated by Django 3.2.6 on 2022-03-03 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_application', '0007_alter_jobapplication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
