# Generated by Django 3.2.6 on 2022-03-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0008_alter_jobapplication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='user',
        ),
    ]
