# Generated by Django 3.2.6 on 2022-03-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0009_remove_jobapplication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='proof_business',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='proof_id',
        ),
    ]
