# Generated by Django 3.2.6 on 2022-03-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0011_auto_20220303_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='proof_business',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='proof_id',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
